/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jason
 */
public class Crypto2 extends javax.swing.JFrame {

    /**
     * Creates new form Crypto2
     */
    public Crypto2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Project = new javax.swing.JLabel();
        Theme = new javax.swing.JLabel();
        BlowfishPanelWelcome = new javax.swing.JPanel();
        BlowfishIntro = new javax.swing.JLabel();
        ThemePicture10 = new javax.swing.JLabel();
        BlowfishDes = new javax.swing.JButton();
        BlowfishQ = new javax.swing.JButton();
        BlowfishDescription = new javax.swing.JPanel();
        BlowfishTitle = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea27 = new javax.swing.JTextArea();
        ThemePicture23 = new javax.swing.JLabel();
        BlowfishBB = new javax.swing.JButton();
        BlowfishPanel = new javax.swing.JPanel();
        BlowfishReturn = new javax.swing.JButton();
        AESPanelWelcome = new javax.swing.JPanel();
        AESIntro = new javax.swing.JLabel();
        ThemePicture11 = new javax.swing.JLabel();
        AESDes = new javax.swing.JButton();
        AESQ = new javax.swing.JButton();
        AESDescription = new javax.swing.JPanel();
        AEStitle = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea28 = new javax.swing.JTextArea();
        ThemePicture24 = new javax.swing.JLabel();
        AESBack = new javax.swing.JButton();
        AESPanel = new javax.swing.JPanel();
        AESTitle = new javax.swing.JLabel();
        AESReturn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        PrivateKey = new javax.swing.JMenu();
        Blowfish = new javax.swing.JMenuItem();
        AES = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(885, 750));
        setMinimumSize(new java.awt.Dimension(885, 750));
        setPreferredSize(new java.awt.Dimension(885, 750));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(20, 58, 83));
        WelcomePanel.setForeground(new java.awt.Color(48, 87, 120));

        Welcome.setFont(new java.awt.Font("Courier", 0, 48)); // NOI18N
        Welcome.setForeground(new java.awt.Color(218, 233, 216));
        Welcome.setText("<html><strong>Part 2");

        Project.setFont(new java.awt.Font("Courier", 0, 16)); // NOI18N
        Project.setForeground(new java.awt.Color(218, 233, 216));
        Project.setText("Project H98230-17-0322");

        Theme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/theme2.png"))); // NOI18N

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(Project))
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Theme)
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Project)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(Theme))
        );

        MainPanel.add(WelcomePanel, "card2");

        BlowfishPanelWelcome.setBackground(new java.awt.Color(255, 255, 255));

        BlowfishIntro.setBackground(new java.awt.Color(255, 255, 255));
        BlowfishIntro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BlowfishIntro.setForeground(new java.awt.Color(48, 87, 120));
        BlowfishIntro.setText("Blowfish");

        ThemePicture10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/theme1.png"))); // NOI18N

        BlowfishDes.setBackground(new java.awt.Color(77, 132, 155));
        BlowfishDes.setForeground(new java.awt.Color(255, 255, 255));
        BlowfishDes.setText("Description");
        BlowfishDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlowfishDesActionPerformed(evt);
            }
        });

        BlowfishQ.setBackground(new java.awt.Color(77, 132, 155));
        BlowfishQ.setForeground(new java.awt.Color(255, 255, 255));
        BlowfishQ.setText("Questions");
        BlowfishQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlowfishQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BlowfishPanelWelcomeLayout = new javax.swing.GroupLayout(BlowfishPanelWelcome);
        BlowfishPanelWelcome.setLayout(BlowfishPanelWelcomeLayout);
        BlowfishPanelWelcomeLayout.setHorizontalGroup(
            BlowfishPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlowfishPanelWelcomeLayout.createSequentialGroup()
                .addComponent(ThemePicture10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BlowfishPanelWelcomeLayout.createSequentialGroup()
                .addGroup(BlowfishPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BlowfishPanelWelcomeLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(BlowfishDes)
                        .addGap(66, 66, 66)
                        .addComponent(BlowfishQ))
                    .addGroup(BlowfishPanelWelcomeLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(BlowfishIntro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BlowfishPanelWelcomeLayout.setVerticalGroup(
            BlowfishPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlowfishPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(BlowfishIntro)
                .addGap(18, 18, 18)
                .addGroup(BlowfishPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlowfishDes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlowfishQ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148)
                .addComponent(ThemePicture10))
        );

        MainPanel.add(BlowfishPanelWelcome, "card51");

        BlowfishDescription.setBackground(new java.awt.Color(255, 255, 255));

        BlowfishTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        BlowfishTitle.setForeground(new java.awt.Color(48, 87, 120));
        BlowfishTitle.setText("Blowfish ");

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea27.setColumns(20);
        jTextArea27.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        jTextArea27.setLineWrap(true);
        jTextArea27.setRows(5);
        jTextArea27.setText("- Blowfish is a symmetric-key block cipher designed by Bruce Schneier\n- No effective crytanalysis of it has been found to date\n- It was originally designed as an alternative to DES\n- Like 3DES, it has 16 rounds and uses the Feistel Network\n- It uses block sizes of 64 bits and key sizes from 32-448 bits\n- However, Twofish is more widely used due to it's larger block sizes");
        jTextArea27.setWrapStyleWord(true);
        jScrollPane6.setViewportView(jTextArea27);

        ThemePicture23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/theme1.png"))); // NOI18N

        BlowfishBB.setBackground(new java.awt.Color(77, 132, 155));
        BlowfishBB.setForeground(new java.awt.Color(255, 255, 255));
        BlowfishBB.setText("Return");
        BlowfishBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlowfishBBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BlowfishDescriptionLayout = new javax.swing.GroupLayout(BlowfishDescription);
        BlowfishDescription.setLayout(BlowfishDescriptionLayout);
        BlowfishDescriptionLayout.setHorizontalGroup(
            BlowfishDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlowfishDescriptionLayout.createSequentialGroup()
                .addGroup(BlowfishDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThemePicture23)
                    .addGroup(BlowfishDescriptionLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(BlowfishTitle))
                    .addGroup(BlowfishDescriptionLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BlowfishDescriptionLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(BlowfishBB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BlowfishDescriptionLayout.setVerticalGroup(
            BlowfishDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlowfishDescriptionLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(BlowfishTitle)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(BlowfishBB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThemePicture23))
        );

        MainPanel.add(BlowfishDescription, "card87");

        BlowfishPanel.setBackground(new java.awt.Color(255, 255, 255));

        BlowfishReturn.setBackground(new java.awt.Color(77, 132, 155));
        BlowfishReturn.setForeground(new java.awt.Color(255, 255, 255));
        BlowfishReturn.setText("Return");
        BlowfishReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlowfishReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BlowfishPanelLayout = new javax.swing.GroupLayout(BlowfishPanel);
        BlowfishPanel.setLayout(BlowfishPanelLayout);
        BlowfishPanelLayout.setHorizontalGroup(
            BlowfishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlowfishPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BlowfishReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BlowfishPanelLayout.setVerticalGroup(
            BlowfishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlowfishPanelLayout.createSequentialGroup()
                .addContainerGap(706, Short.MAX_VALUE)
                .addComponent(BlowfishReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        MainPanel.add(BlowfishPanel, "card37");

        AESPanelWelcome.setBackground(new java.awt.Color(255, 255, 255));

        AESIntro.setBackground(new java.awt.Color(255, 255, 255));
        AESIntro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AESIntro.setForeground(new java.awt.Color(48, 87, 120));
        AESIntro.setText("AES");

        ThemePicture11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/theme1.png"))); // NOI18N

        AESDes.setBackground(new java.awt.Color(77, 132, 155));
        AESDes.setForeground(new java.awt.Color(255, 255, 255));
        AESDes.setText("Description");
        AESDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AESDesActionPerformed(evt);
            }
        });

        AESQ.setBackground(new java.awt.Color(77, 132, 155));
        AESQ.setForeground(new java.awt.Color(255, 255, 255));
        AESQ.setText("Questions");
        AESQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AESQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AESPanelWelcomeLayout = new javax.swing.GroupLayout(AESPanelWelcome);
        AESPanelWelcome.setLayout(AESPanelWelcomeLayout);
        AESPanelWelcomeLayout.setHorizontalGroup(
            AESPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AESPanelWelcomeLayout.createSequentialGroup()
                .addComponent(ThemePicture11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AESPanelWelcomeLayout.createSequentialGroup()
                .addGroup(AESPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AESPanelWelcomeLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(AESDes)
                        .addGap(66, 66, 66)
                        .addComponent(AESQ))
                    .addGroup(AESPanelWelcomeLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(AESIntro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AESPanelWelcomeLayout.setVerticalGroup(
            AESPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AESPanelWelcomeLayout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(AESIntro)
                .addGap(18, 18, 18)
                .addGroup(AESPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AESDes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AESQ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148)
                .addComponent(ThemePicture11))
        );

        MainPanel.add(AESPanelWelcome, "card52");

        AESDescription.setBackground(new java.awt.Color(255, 255, 255));

        AEStitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        AEStitle.setForeground(new java.awt.Color(48, 87, 120));
        AEStitle.setText("Advanced Encryption Standard");

        jScrollPane7.setBorder(null);

        jTextArea28.setColumns(20);
        jTextArea28.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        jTextArea28.setLineWrap(true);
        jTextArea28.setRows(5);
        jTextArea28.setText("- AES was created by Vincent Rijmen and Joan Daemen who submitted a proposal to NIST during the AES selection process. \n- AES uses 10, 12 or 14 rounds for the 128, 192 and 256 bit key size, respectively. \n- AES is currently standard for the U.S government\n- It is a symmetric-key algorithm \n- While there have been proposals for AES attacks that are computationally faster than a brute-force attack, they are not computationally feasible.");
        jTextArea28.setWrapStyleWord(true);
        jScrollPane7.setViewportView(jTextArea28);

        ThemePicture24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/theme1.png"))); // NOI18N

        AESBack.setBackground(new java.awt.Color(77, 132, 155));
        AESBack.setForeground(new java.awt.Color(255, 255, 255));
        AESBack.setText("Return");
        AESBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AESBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AESDescriptionLayout = new javax.swing.GroupLayout(AESDescription);
        AESDescription.setLayout(AESDescriptionLayout);
        AESDescriptionLayout.setHorizontalGroup(
            AESDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AESDescriptionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(AESDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThemePicture24)
                    .addGroup(AESDescriptionLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AESDescriptionLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(AESBack))
                    .addGroup(AESDescriptionLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(AEStitle)))
                .addGap(28, 28, 28))
        );
        AESDescriptionLayout.setVerticalGroup(
            AESDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AESDescriptionLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(AEStitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AESBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThemePicture24))
        );

        MainPanel.add(AESDescription, "card87");

        AESPanel.setBackground(new java.awt.Color(255, 255, 255));

        AESTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AESTitle.setForeground(new java.awt.Color(48, 87, 120));
        AESTitle.setText("AES");

        AESReturn.setBackground(new java.awt.Color(77, 132, 155));
        AESReturn.setForeground(new java.awt.Color(255, 255, 255));
        AESReturn.setText("Return");
        AESReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AESReturnActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(77, 132, 155));
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/theme1.png"))); // NOI18N

        javax.swing.GroupLayout AESPanelLayout = new javax.swing.GroupLayout(AESPanel);
        AESPanel.setLayout(AESPanelLayout);
        AESPanelLayout.setHorizontalGroup(
            AESPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AESPanelLayout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(AESTitle))
            .addComponent(jLabel32)
            .addGroup(AESPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(AESReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AESPanelLayout.setVerticalGroup(
            AESPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AESPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(AESTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AESReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel32))
        );

        MainPanel.add(AESPanel, "card38");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        PrivateKey.setText("Private Key");

        Blowfish.setText("Blowfish");
        Blowfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlowfishActionPerformed(evt);
            }
        });
        PrivateKey.add(Blowfish);

        AES.setText("AES");
        AES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AESActionPerformed(evt);
            }
        });
        PrivateKey.add(AES);

        jMenuBar1.add(PrivateKey);

        jMenu3.setText("Part One");

        jMenuItem1.setText("Return");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BlowfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlowfishActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(BlowfishPanelWelcome);
        MainPanel.repaint();
        MainPanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_BlowfishActionPerformed

    private void AESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AESActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(AESPanelWelcome);
        MainPanel.repaint();
        MainPanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_AESActionPerformed

    private void BlowfishDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlowfishDesActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(BlowfishDescription);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BlowfishDesActionPerformed

    private void BlowfishQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlowfishQActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(BlowfishPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BlowfishQActionPerformed

    private void BlowfishBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlowfishBBActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(BlowfishPanelWelcome);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BlowfishBBActionPerformed

    private void BlowfishReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlowfishReturnActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(BlowfishPanelWelcome);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BlowfishReturnActionPerformed

    private void AESDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AESDesActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(AESDescription);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_AESDesActionPerformed

    private void AESQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AESQActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(AESPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_AESQActionPerformed

    private void AESBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AESBackActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(AESPanelWelcome);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_AESBackActionPerformed

    private void AESReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AESReturnActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(AESPanelWelcome);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_AESReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crypto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crypto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crypto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crypto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crypto2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AES;
    private javax.swing.JButton AESBack;
    private javax.swing.JButton AESDes;
    private javax.swing.JPanel AESDescription;
    private javax.swing.JLabel AESIntro;
    private javax.swing.JPanel AESPanel;
    private javax.swing.JPanel AESPanelWelcome;
    private javax.swing.JButton AESQ;
    private javax.swing.JButton AESReturn;
    private javax.swing.JLabel AESTitle;
    private javax.swing.JLabel AEStitle;
    private javax.swing.JMenuItem Blowfish;
    private javax.swing.JButton BlowfishBB;
    private javax.swing.JButton BlowfishDes;
    private javax.swing.JPanel BlowfishDescription;
    private javax.swing.JLabel BlowfishIntro;
    private javax.swing.JPanel BlowfishPanel;
    private javax.swing.JPanel BlowfishPanelWelcome;
    private javax.swing.JButton BlowfishQ;
    private javax.swing.JButton BlowfishReturn;
    private javax.swing.JLabel BlowfishTitle;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenu PrivateKey;
    private javax.swing.JLabel Project;
    private javax.swing.JLabel Theme;
    private javax.swing.JLabel ThemePicture10;
    private javax.swing.JLabel ThemePicture11;
    private javax.swing.JLabel ThemePicture23;
    private javax.swing.JLabel ThemePicture24;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    // End of variables declaration//GEN-END:variables
}
