
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. test
 */

/**
 *
 * @author hannahmclaughlin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        FSULOGO = new javax.swing.JLabel();
        CaesarPanel = new javax.swing.JPanel();
        CaesarTitle = new javax.swing.JLabel();
        Warning = new javax.swing.JLabel();
        Ciphertext_Caesar = new javax.swing.JLabel();
        Submission = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AtbashPanel = new javax.swing.JPanel();
        AtbashTitle = new javax.swing.JLabel();
        Warning1 = new javax.swing.JLabel();
        Ciphertext_Atbash = new javax.swing.JLabel();
        Submission1 = new javax.swing.JTextField();
        Submit1 = new javax.swing.JButton();
        VigenerePanel = new javax.swing.JPanel();
        VigenereTitle = new javax.swing.JLabel();
        Warning2 = new javax.swing.JLabel();
        Ciphertext_Vigenere = new javax.swing.JLabel();
        Submission2 = new javax.swing.JTextField();
        Submit2 = new javax.swing.JButton();
        ECBPanel = new javax.swing.JPanel();
        ECB_Picture = new javax.swing.JLabel();
        Answer1 = new javax.swing.JTextField();
        ECB_Button = new javax.swing.JButton();
        Q1 = new javax.swing.JLabel();
        Correct_ECB = new javax.swing.JPanel();
        Correct_Pic = new javax.swing.JLabel();
        Correct1 = new javax.swing.JLabel();
        FeistelPanel = new javax.swing.JPanel();
        Feistel_Pic = new javax.swing.JLabel();
        Feistel_Intro = new javax.swing.JLabel();
        Feistel_Entry = new javax.swing.JTextField();
        Feistel_Button = new javax.swing.JButton();
        RSAPanel = new javax.swing.JPanel();
        RSAQ1 = new javax.swing.JLabel();
        RSAHeader = new javax.swing.JLabel();
        RSAA1_1 = new javax.swing.JTextField();
        RSAQ1_1 = new javax.swing.JLabel();
        RSAB1_1 = new javax.swing.JButton();
        RSAQ1_2 = new javax.swing.JLabel();
        RSAA1_2 = new javax.swing.JTextField();
        RSAB1_2 = new javax.swing.JButton();
        RSAQ1_3 = new javax.swing.JLabel();
        RSAA1_3 = new javax.swing.JTextField();
        RSAB1_3 = new javax.swing.JButton();
        ElGamalPanel = new javax.swing.JPanel();
        ElGamalHeader = new javax.swing.JLabel();
        EGQ1 = new javax.swing.JLabel();
        EGQ1_1 = new javax.swing.JLabel();
        EGA1_1 = new javax.swing.JTextField();
        EGB1_1 = new javax.swing.JButton();
        EGQ1_2 = new javax.swing.JLabel();
        EGA1_2 = new javax.swing.JTextField();
        EGB1_2 = new javax.swing.JButton();
        SHAPanel = new javax.swing.JPanel();
        SHA_Text = new javax.swing.JTextField();
        SHA_Button = new javax.swing.JButton();
        SHA_Output = new javax.swing.JLabel();
        SHA_Header1 = new javax.swing.JLabel();
        SHA_Questions = new javax.swing.JLabel();
        SHAQ1 = new javax.swing.JLabel();
        SHAQ2 = new javax.swing.JLabel();
        FormerSHA = new javax.swing.JLabel();
        Current = new javax.swing.JLabel();
        Former = new javax.swing.JLabel();
        SHAB1 = new javax.swing.JButton();
        SHAA2 = new javax.swing.JTextField();
        SHAB2 = new javax.swing.JButton();
        SHAQ3 = new javax.swing.JLabel();
        SHAA3 = new javax.swing.JTextField();
        SHAB3 = new javax.swing.JButton();
        SHAA1 = new javax.swing.JTextField();
        DHPanel = new javax.swing.JPanel();
        DHDiagram = new javax.swing.JLabel();
        DHButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DHPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        DHPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        DHPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        DHPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        DHPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        CBCMAC = new javax.swing.JPanel();
        CBCMACTitle = new javax.swing.JLabel();
        Question1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        Question3_1 = new javax.swing.JLabel();
        Question4 = new javax.swing.JLabel();
        Question5 = new javax.swing.JLabel();
        Question5_1 = new javax.swing.JLabel();
        Question5_2 = new javax.swing.JLabel();
        True = new javax.swing.JLabel();
        False = new javax.swing.JLabel();
        T1 = new javax.swing.JRadioButton();
        F1 = new javax.swing.JRadioButton();
        T2 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        T3 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        T4 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        T5 = new javax.swing.JRadioButton();
        F5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        Ciphers = new javax.swing.JMenu();
        SubstitutionCiphers = new javax.swing.JMenu();
        Caesar = new javax.swing.JMenuItem();
        Atbash = new javax.swing.JMenuItem();
        Vigenere = new javax.swing.JMenuItem();
        BlockCiphers = new javax.swing.JMenu();
        Feistel = new javax.swing.JMenuItem();
        RC5 = new javax.swing.JMenuItem();
        TripDES = new javax.swing.JMenuItem();
        StreamCiphers = new javax.swing.JMenu();
        OneTimePad = new javax.swing.JMenuItem();
        Synchronous = new javax.swing.JMenuItem();
        SSynchronizing = new javax.swing.JMenuItem();
        LinearFeedback = new javax.swing.JMenuItem();
        Entropy = new javax.swing.JMenuItem();
        EncryptionModes = new javax.swing.JMenu();
        ECB = new javax.swing.JMenuItem();
        CBC = new javax.swing.JMenuItem();
        CTR = new javax.swing.JMenuItem();
        Authentication = new javax.swing.JMenu();
        PAP = new javax.swing.JMenuItem();
        CHAP = new javax.swing.JMenuItem();
        Kerberos = new javax.swing.JMenuItem();
        CBC_MAC = new javax.swing.JMenuItem();
        DigitalSignatures = new javax.swing.JMenu();
        Hashing = new javax.swing.JMenu();
        SHA = new javax.swing.JMenuItem();
        MD5 = new javax.swing.JMenuItem();
        RSASignature = new javax.swing.JMenuItem();
        PublicKey = new javax.swing.JMenu();
        RSA = new javax.swing.JMenuItem();
        ELGamal = new javax.swing.JMenuItem();
        DiffieHellman = new javax.swing.JMenuItem();
        PrivateKey = new javax.swing.JMenu();
        Blowfish = new javax.swing.JMenuItem();
        AES = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Dev = new javax.swing.JMenuItem();

        buttonGroup3.add(jRadioButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 255));

        Welcome.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        Welcome.setText("Welcome to the FSU Cryptography Module");

        FSULOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/fsu-seal-full-color.png"))); // NOI18N

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(FSULOGO))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FSULOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        MainPanel.add(WelcomePanel, "card2");

        CaesarPanel.setBackground(new java.awt.Color(204, 204, 255));

        CaesarTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        CaesarTitle.setText("Let's practice breaking a Caesar Cipher!");

        Warning.setText("Please write a script to decrypt the following ciphertext. Instructors may ask students to demo or submit their code. ");

        Ciphertext_Caesar.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Ciphertext_Caesar.setText("Phrase: vogvizvetv zj kyv kvrtyvi fw rcc kyzexj ");

        Submission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmissionActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter the plaintext answer in lowercase");

        javax.swing.GroupLayout CaesarPanelLayout = new javax.swing.GroupLayout(CaesarPanel);
        CaesarPanel.setLayout(CaesarPanelLayout);
        CaesarPanelLayout.setHorizontalGroup(
            CaesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(CaesarTitle))
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Warning))
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Ciphertext_Caesar))
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(Submission, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(Submit))
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1))
        );
        CaesarPanelLayout.setVerticalGroup(
            CaesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaesarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CaesarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Warning)
                .addGap(84, 84, 84)
                .addComponent(Ciphertext_Caesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(Submission, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Submit))
        );

        MainPanel.add(CaesarPanel, "card3");

        AtbashPanel.setBackground(new java.awt.Color(204, 255, 204));

        AtbashTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        AtbashTitle.setText("Let's practice breaking an Atbash Cipher!");

        Warning1.setText("Please write a script to decrypt the following ciphertext. Instructors may ask students to demo or submit their code. ");

        Ciphertext_Atbash.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Ciphertext_Atbash.setText("Phrase: vhmk ijpt e uavuav uigjev (key: caesar) ");

        Submission1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submission1ActionPerformed(evt);
            }
        });

        Submit1.setText("Submit");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AtbashPanelLayout = new javax.swing.GroupLayout(AtbashPanel);
        AtbashPanel.setLayout(AtbashPanelLayout);
        AtbashPanelLayout.setHorizontalGroup(
            AtbashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtbashPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(AtbashTitle))
            .addGroup(AtbashPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Warning1))
            .addGroup(AtbashPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Ciphertext_Atbash))
            .addGroup(AtbashPanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(Submission1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(AtbashPanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(Submit1))
        );
        AtbashPanelLayout.setVerticalGroup(
            AtbashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtbashPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(AtbashTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Warning1)
                .addGap(84, 84, 84)
                .addComponent(Ciphertext_Atbash)
                .addGap(90, 90, 90)
                .addComponent(Submission1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Submit1))
        );

        MainPanel.add(AtbashPanel, "card4");

        VigenerePanel.setBackground(new java.awt.Color(255, 204, 204));

        VigenereTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        VigenereTitle.setText("Let's practice breaking a Vigenere Cipher!");

        Warning2.setText("Please write a script to decrypt the following ciphertext. Instructors may ask students to demo or submit their code. ");

        Ciphertext_Vigenere.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Ciphertext_Vigenere.setText("Phrase: mlgsrmt zylfg gsrh rh hvxfiv");

        Submission2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submission2ActionPerformed(evt);
            }
        });

        Submit2.setText("Submit");
        Submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VigenerePanelLayout = new javax.swing.GroupLayout(VigenerePanel);
        VigenerePanel.setLayout(VigenerePanelLayout);
        VigenerePanelLayout.setHorizontalGroup(
            VigenerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VigenerePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(VigenereTitle))
            .addGroup(VigenerePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Warning2))
            .addGroup(VigenerePanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Ciphertext_Vigenere))
            .addGroup(VigenerePanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(Submission2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(VigenerePanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(Submit2))
        );
        VigenerePanelLayout.setVerticalGroup(
            VigenerePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VigenerePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(VigenereTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Warning2)
                .addGap(74, 74, 74)
                .addComponent(Ciphertext_Vigenere)
                .addGap(100, 100, 100)
                .addComponent(Submission2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Submit2))
        );

        MainPanel.add(VigenerePanel, "card5");

        ECBPanel.setBackground(new java.awt.Color(255, 255, 255));

        ECB_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ECB.png"))); // NOI18N
        ECB_Picture.setText("jLabel4");

        Answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1ActionPerformed(evt);
            }
        });

        ECB_Button.setText("Enter");
        ECB_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECB_ButtonActionPerformed(evt);
            }
        });

        Q1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Q1.setText("What does the following picture enrypted with 3DES ECB say?");

        javax.swing.GroupLayout ECBPanelLayout = new javax.swing.GroupLayout(ECBPanel);
        ECBPanel.setLayout(ECBPanelLayout);
        ECBPanelLayout.setHorizontalGroup(
            ECBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ECBPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Q1))
            .addGroup(ECBPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(ECB_Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ECBPanelLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(ECB_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ECBPanelLayout.setVerticalGroup(
            ECBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ECBPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ECB_Picture)
                .addGap(24, 24, 24)
                .addGroup(ECBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECB_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MainPanel.add(ECBPanel, "card6");

        Correct_ECB.setBackground(new java.awt.Color(255, 255, 255));

        Correct_Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Test.png"))); // NOI18N
        Correct_Pic.setText("jLabel2");

        Correct1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Correct1.setForeground(new java.awt.Color(51, 255, 51));
        Correct1.setText("CORRECT!");

        javax.swing.GroupLayout Correct_ECBLayout = new javax.swing.GroupLayout(Correct_ECB);
        Correct_ECB.setLayout(Correct_ECBLayout);
        Correct_ECBLayout.setHorizontalGroup(
            Correct_ECBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Correct_ECBLayout.createSequentialGroup()
                .addGroup(Correct_ECBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Correct_ECBLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(Correct_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Correct_ECBLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(Correct1)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        Correct_ECBLayout.setVerticalGroup(
            Correct_ECBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Correct_ECBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Correct1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Correct_Pic)
                .addGap(103, 103, 103))
        );

        MainPanel.add(Correct_ECB, "card7");

        FeistelPanel.setBackground(new java.awt.Color(255, 255, 255));

        Feistel_Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/feistel1.jpg"))); // NOI18N

        Feistel_Intro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Feistel_Intro.setText("What is the final 8 bit value?");

        Feistel_Entry.setText("Answer Here!");
        Feistel_Entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feistel_EntryActionPerformed(evt);
            }
        });

        Feistel_Button.setText("Enter");
        Feistel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feistel_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeistelPanelLayout = new javax.swing.GroupLayout(FeistelPanel);
        FeistelPanel.setLayout(FeistelPanelLayout);
        FeistelPanelLayout.setHorizontalGroup(
            FeistelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeistelPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(Feistel_Intro))
            .addGroup(FeistelPanelLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(Feistel_Pic)
                .addGap(112, 112, 112)
                .addComponent(Feistel_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Feistel_Button))
        );
        FeistelPanelLayout.setVerticalGroup(
            FeistelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeistelPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Feistel_Intro)
                .addGroup(FeistelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeistelPanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(FeistelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Feistel_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Feistel_Entry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FeistelPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Feistel_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        MainPanel.add(FeistelPanel, "card8");

        RSAPanel.setBackground(new java.awt.Color(255, 255, 255));

        RSAQ1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RSAQ1.setText("Alice wants to send a message to Bob. Given p = 3, q = 11, and e = 3 answer the following questions:");

        RSAHeader.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        RSAHeader.setForeground(new java.awt.Color(255, 0, 0));
        RSAHeader.setText("RSA Practice Problems");

        RSAA1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSAA1_1ActionPerformed(evt);
            }
        });

        RSAQ1_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RSAQ1_1.setText("1. What is Bob’s public key? Format: (n,e)");

        RSAB1_1.setText("Enter");

        RSAQ1_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RSAQ1_2.setText("2. Alice wants to send M = 7, what is C?");

        RSAB1_2.setText("Enter");

        RSAQ1_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RSAQ1_3.setText("3. What is Bob’s private key? Format: (n,d)");

        RSAB1_3.setText("Enter");

        javax.swing.GroupLayout RSAPanelLayout = new javax.swing.GroupLayout(RSAPanel);
        RSAPanel.setLayout(RSAPanelLayout);
        RSAPanelLayout.setHorizontalGroup(
            RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RSAPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RSAHeader)
                .addGap(243, 243, 243))
            .addGroup(RSAPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RSAQ1)
                    .addGroup(RSAPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RSAQ1_1)
                            .addGroup(RSAPanelLayout.createSequentialGroup()
                                .addComponent(RSAA1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RSAB1_1))
                            .addComponent(RSAQ1_2)
                            .addGroup(RSAPanelLayout.createSequentialGroup()
                                .addComponent(RSAA1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RSAB1_2))
                            .addComponent(RSAQ1_3)
                            .addGroup(RSAPanelLayout.createSequentialGroup()
                                .addComponent(RSAA1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RSAB1_3)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        RSAPanelLayout.setVerticalGroup(
            RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RSAPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(RSAHeader)
                .addGap(18, 18, 18)
                .addComponent(RSAQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RSAQ1_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RSAA1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RSAB1_1))
                .addGap(55, 55, 55)
                .addComponent(RSAQ1_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RSAA1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RSAB1_2))
                .addGap(65, 65, 65)
                .addComponent(RSAQ1_3)
                .addGap(18, 18, 18)
                .addGroup(RSAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RSAA1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RSAB1_3))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        MainPanel.add(RSAPanel, "card9");

        ElGamalPanel.setBackground(new java.awt.Color(255, 255, 255));

        ElGamalHeader.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ElGamalHeader.setForeground(new java.awt.Color(255, 0, 0));
        ElGamalHeader.setText("EL Gamal Practice Problems");

        EGQ1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EGQ1.setText("Bob generates p and g where p = 11, and g = 5. Then, Bob selects a random number x = 3. Given this information solve the following problems:");

        EGQ1_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EGQ1_1.setText("1. What is Bob’s public key?");

        EGA1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EGA1_1ActionPerformed(evt);
            }
        });

        EGB1_1.setText("Enter");
        EGB1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EGB1_1ActionPerformed(evt);
            }
        });

        EGQ1_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EGQ1_2.setText("2. Alice wants to send message M = 4 to Bob, she chooses a random integer k = 4. What is the encrypted message Alice sends?");

        EGA1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EGA1_2ActionPerformed(evt);
            }
        });

        EGB1_2.setText("Enter");

        javax.swing.GroupLayout ElGamalPanelLayout = new javax.swing.GroupLayout(ElGamalPanel);
        ElGamalPanel.setLayout(ElGamalPanelLayout);
        ElGamalPanelLayout.setHorizontalGroup(
            ElGamalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElGamalPanelLayout.createSequentialGroup()
                .addGroup(ElGamalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ElGamalPanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(ElGamalHeader))
                    .addGroup(ElGamalPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(ElGamalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EGQ1_1)
                            .addComponent(EGQ1)
                            .addGroup(ElGamalPanelLayout.createSequentialGroup()
                                .addComponent(EGA1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EGB1_1))
                            .addComponent(EGQ1_2)
                            .addGroup(ElGamalPanelLayout.createSequentialGroup()
                                .addComponent(EGA1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EGB1_2)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        ElGamalPanelLayout.setVerticalGroup(
            ElGamalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElGamalPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ElGamalHeader)
                .addGap(18, 18, 18)
                .addComponent(EGQ1)
                .addGap(34, 34, 34)
                .addComponent(EGQ1_1)
                .addGap(30, 30, 30)
                .addGroup(ElGamalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EGA1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EGB1_1))
                .addGap(57, 57, 57)
                .addComponent(EGQ1_2)
                .addGap(39, 39, 39)
                .addGroup(ElGamalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EGA1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EGB1_2))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        MainPanel.add(ElGamalPanel, "card10");

        SHAPanel.setBackground(new java.awt.Color(255, 255, 255));

        SHA_Button.setText("Enter");
        SHA_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHA_ButtonActionPerformed(evt);
            }
        });

        SHA_Output.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SHA_Output.setText("SHA-256 Text");

        SHA_Header1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SHA_Header1.setText("Enter any text to see its SHA-256 output!");

        SHA_Questions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SHA_Questions.setText("Questions:");

        SHAQ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SHAQ1.setText("1. What is the length (in bytes) of all SHA-256 outputs?");

        SHAQ2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SHAQ2.setText("2. For any hash function, the same input will generate different output? T/F");

        FormerSHA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Current.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Current.setText("Current:");

        Former.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Former.setText("Former:");

        SHAB1.setText("jButton1");

        SHAA2.setText("jTextField2");

        SHAB2.setText("jButton2");

        SHAQ3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SHAQ3.setText("3. Not sure yet?");

        SHAA3.setText("jTextField3");

        SHAB3.setText("jButton3");

        SHAA1.setText("jTextField1");

        javax.swing.GroupLayout SHAPanelLayout = new javax.swing.GroupLayout(SHAPanel);
        SHAPanel.setLayout(SHAPanelLayout);
        SHAPanelLayout.setHorizontalGroup(
            SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHAPanelLayout.createSequentialGroup()
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SHAPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Current)
                            .addComponent(Former))
                        .addGap(18, 18, 18)
                        .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SHA_Output)
                            .addGroup(SHAPanelLayout.createSequentialGroup()
                                .addComponent(SHA_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SHA_Button))
                            .addComponent(FormerSHA)))
                    .addGroup(SHAPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SHA_Questions)
                            .addComponent(SHA_Header1)
                            .addComponent(SHAQ1)
                            .addComponent(SHAQ2)
                            .addGroup(SHAPanelLayout.createSequentialGroup()
                                .addComponent(SHAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SHAB1))
                            .addGroup(SHAPanelLayout.createSequentialGroup()
                                .addComponent(SHAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SHAB2))
                            .addComponent(SHAQ3)
                            .addGroup(SHAPanelLayout.createSequentialGroup()
                                .addComponent(SHAA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SHAB3)))))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        SHAPanelLayout.setVerticalGroup(
            SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SHAPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(SHA_Header1)
                .addGap(46, 46, 46)
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SHA_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SHA_Button))
                .addGap(43, 43, 43)
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SHA_Output)
                    .addComponent(Current))
                .addGap(18, 18, 18)
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormerSHA)
                    .addComponent(Former))
                .addGap(27, 27, 27)
                .addComponent(SHA_Questions)
                .addGap(36, 36, 36)
                .addComponent(SHAQ1)
                .addGap(18, 18, 18)
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SHAB1)
                    .addComponent(SHAA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SHAQ2)
                .addGap(18, 18, 18)
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SHAA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SHAB2))
                .addGap(18, 18, 18)
                .addComponent(SHAQ3)
                .addGap(18, 18, 18)
                .addGroup(SHAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SHAA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SHAB3))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        MainPanel.add(SHAPanel, "card11");

        DHPanel.setBackground(new java.awt.Color(255, 255, 255));

        DHDiagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/DH1.png"))); // NOI18N

        DHButton.setText("Next");
        DHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DHButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("The following is an elementary example of Diffie-Hellman\nkey exchange between Alice and Bob. This example has a passive\nman-in-the middle attack performed by Eve. Click next to go\nto the next diagram.\n");

        javax.swing.GroupLayout DHPanelLayout = new javax.swing.GroupLayout(DHPanel);
        DHPanel.setLayout(DHPanelLayout);
        DHPanelLayout.setHorizontalGroup(
            DHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanelLayout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addGroup(DHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanelLayout.createSequentialGroup()
                        .addGroup(DHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DHDiagram)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanelLayout.createSequentialGroup()
                        .addComponent(DHButton)
                        .addGap(407, 407, 407))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanelLayout.createSequentialGroup()
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        DHPanelLayout.setVerticalGroup(
            DHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DHDiagram)
                .addGap(46, 46, 46)
                .addComponent(DHButton)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        MainPanel.add(DHPanel, "card12");

        DHPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/DH2.png"))); // NOI18N

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DHPanel1Layout = new javax.swing.GroupLayout(DHPanel1);
        DHPanel1.setLayout(DHPanel1Layout);
        DHPanel1Layout.setHorizontalGroup(
            DHPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel1Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(DHPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(409, 409, 409))))
        );
        DHPanel1Layout.setVerticalGroup(
            DHPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        MainPanel.add(DHPanel1, "card12");

        DHPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/DH3.png"))); // NOI18N

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DHPanel2Layout = new javax.swing.GroupLayout(DHPanel2);
        DHPanel2.setLayout(DHPanel2Layout);
        DHPanel2Layout.setHorizontalGroup(
            DHPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel2Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(DHPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(409, 409, 409))))
        );
        DHPanel2Layout.setVerticalGroup(
            DHPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel4)
                .addGap(51, 51, 51)
                .addComponent(jButton3)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        MainPanel.add(DHPanel2, "card12");

        DHPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/DH4.png"))); // NOI18N

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DHPanel3Layout = new javax.swing.GroupLayout(DHPanel3);
        DHPanel3.setLayout(DHPanel3Layout);
        DHPanel3Layout.setHorizontalGroup(
            DHPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel3Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(DHPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(409, 409, 409))))
        );
        DHPanel3Layout.setVerticalGroup(
            DHPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel3Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addComponent(jButton4)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        MainPanel.add(DHPanel3, "card12");

        DHPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/DH5.png"))); // NOI18N

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DHPanel4Layout = new javax.swing.GroupLayout(DHPanel4);
        DHPanel4.setLayout(DHPanel4Layout);
        DHPanel4Layout.setHorizontalGroup(
            DHPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel4Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(DHPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel4Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(409, 409, 409))))
        );
        DHPanel4Layout.setVerticalGroup(
            DHPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel6)
                .addGap(51, 51, 51)
                .addComponent(jButton5)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        MainPanel.add(DHPanel4, "card12");

        DHPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/DH6.png"))); // NOI18N

        jButton6.setText("jButton1");

        javax.swing.GroupLayout DHPanel5Layout = new javax.swing.GroupLayout(DHPanel5);
        DHPanel5.setLayout(DHPanel5Layout);
        DHPanel5Layout.setHorizontalGroup(
            DHPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel5Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(DHPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DHPanel5Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(409, 409, 409))))
        );
        DHPanel5Layout.setVerticalGroup(
            DHPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DHPanel5Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel7)
                .addGap(51, 51, 51)
                .addComponent(jButton6)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        MainPanel.add(DHPanel5, "card12");

        CBCMAC.setBackground(new java.awt.Color(255, 255, 255));

        CBCMACTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        CBCMACTitle.setText("Breaking the security of CBC-MAC");

        Question1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question1.setText("1) CBC-MAC uses a random IV");

        Question2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question2.setText("2) CBC-MAC does not use an IV");

        Question3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question3.setText("3) CBC-MAC can be viewed as using");

        Question3_1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question3_1.setText("the fixed IV = O^n");

        Question4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question4.setText("4) If CBC-MAC uses a random IV, it will be secure");

        Question5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question5.setText("5) CBC-MAC is secure when authenticating");

        Question5_1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question5_1.setText("messages of different lengths, however, it is not");

        Question5_2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Question5_2.setText("secure in cases when messages are fixed sizes");

        True.setText("True");

        False.setText("False");

        buttonGroup1.add(T1);
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(F1);
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(T2);
        T2.setToolTipText("");
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(F2);

        buttonGroup3.add(T3);

        buttonGroup3.add(F3);

        buttonGroup4.add(T4);

        buttonGroup4.add(F4);

        buttonGroup5.add(T5);
        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });

        buttonGroup5.add(F5);
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CBCMACLayout = new javax.swing.GroupLayout(CBCMAC);
        CBCMAC.setLayout(CBCMACLayout);
        CBCMACLayout.setHorizontalGroup(
            CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBCMACLayout.createSequentialGroup()
                .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(CBCMACTitle))
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question2)
                            .addComponent(Question1)
                            .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question4)
                            .addComponent(Question5)
                            .addComponent(Question5_1)
                            .addComponent(Question5_2))
                        .addGap(58, 58, 58)
                        .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T1)
                            .addComponent(True)
                            .addComponent(T2)
                            .addComponent(T3)
                            .addComponent(T4)
                            .addComponent(T5))
                        .addGap(91, 91, 91)
                        .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F5)
                            .addComponent(F4)
                            .addComponent(F2)
                            .addComponent(False)
                            .addComponent(F1)
                            .addComponent(F3)))
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Question3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jButton1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        CBCMACLayout.setVerticalGroup(
            CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBCMACLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CBCMACTitle)
                .addGap(56, 56, 56)
                .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(True)
                            .addComponent(False))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T1)
                            .addComponent(F1)))
                    .addComponent(Question1))
                .addGap(35, 35, 35)
                .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Question2)
                    .addComponent(T2)
                    .addComponent(F2))
                .addGap(28, 28, 28)
                .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Question3)
                    .addComponent(T3)
                    .addComponent(F3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question3_1)
                .addGap(18, 18, 18)
                .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Question4)
                    .addComponent(T4)
                    .addComponent(F4))
                .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Question5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CBCMACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Question5_1)
                            .addComponent(T5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Question5_2))
                    .addGroup(CBCMACLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(F5)))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        MainPanel.add(CBCMAC, "card18");

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Ciphers.setText("Ciphers");

        SubstitutionCiphers.setText("Substitution Ciphers");

        Caesar.setText("Caesar Cipher");
        Caesar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                CaesarComponentAdded(evt);
            }
        });
        Caesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaesarActionPerformed(evt);
            }
        });
        SubstitutionCiphers.add(Caesar);

        Atbash.setText("Atbash Cipher");
        Atbash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtbashActionPerformed(evt);
            }
        });
        SubstitutionCiphers.add(Atbash);

        Vigenere.setText("Vigenere Cipher");
        Vigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VigenereActionPerformed(evt);
            }
        });
        SubstitutionCiphers.add(Vigenere);

        Ciphers.add(SubstitutionCiphers);

        BlockCiphers.setText("Block Ciphers");

        Feistel.setText("Feistel Network");
        Feistel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeistelActionPerformed(evt);
            }
        });
        BlockCiphers.add(Feistel);

        RC5.setText("RC5");
        BlockCiphers.add(RC5);

        TripDES.setText("3DES");
        TripDES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripDESActionPerformed(evt);
            }
        });
        BlockCiphers.add(TripDES);

        Ciphers.add(BlockCiphers);

        StreamCiphers.setText("Stream Ciphers");

        OneTimePad.setText("One Time Pad");
        StreamCiphers.add(OneTimePad);

        Synchronous.setText("Synchronous");
        StreamCiphers.add(Synchronous);

        SSynchronizing.setText("Self-Synchronizing");
        StreamCiphers.add(SSynchronizing);

        LinearFeedback.setText("Linear-Feedback");
        StreamCiphers.add(LinearFeedback);

        Ciphers.add(StreamCiphers);

        Entropy.setText("Entropy");
        Ciphers.add(Entropy);

        jMenuBar1.add(Ciphers);

        EncryptionModes.setText("Encryption Modes");

        ECB.setText("ECB");
        ECB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECBActionPerformed(evt);
            }
        });
        EncryptionModes.add(ECB);

        CBC.setText("CBC");
        EncryptionModes.add(CBC);

        CTR.setText("CTR");
        EncryptionModes.add(CTR);

        jMenuBar1.add(EncryptionModes);

        Authentication.setText("Authentication");

        PAP.setText("Pap");
        Authentication.add(PAP);

        CHAP.setText("Chap");
        Authentication.add(CHAP);

        Kerberos.setText("Kerberos");
        Authentication.add(Kerberos);

        CBC_MAC.setText("Breakin CBC MAC");
        CBC_MAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBC_MACActionPerformed(evt);
            }
        });
        Authentication.add(CBC_MAC);

        jMenuBar1.add(Authentication);

        DigitalSignatures.setText("Digital Signatures");

        Hashing.setText("Hashing");

        SHA.setText("SHA");
        SHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHAActionPerformed(evt);
            }
        });
        Hashing.add(SHA);

        MD5.setText("MD5");
        Hashing.add(MD5);

        DigitalSignatures.add(Hashing);

        RSASignature.setText("RSA Signature");
        DigitalSignatures.add(RSASignature);

        jMenuBar1.add(DigitalSignatures);

        PublicKey.setText("Public Key");

        RSA.setText("RSA");
        RSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSAActionPerformed(evt);
            }
        });
        PublicKey.add(RSA);

        ELGamal.setText("EL Gamal");
        ELGamal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELGamalActionPerformed(evt);
            }
        });
        PublicKey.add(ELGamal);

        DiffieHellman.setText("Diffie-Hellman");
        DiffieHellman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiffieHellmanActionPerformed(evt);
            }
        });
        PublicKey.add(DiffieHellman);

        jMenuBar1.add(PublicKey);

        PrivateKey.setText("Private Key");

        Blowfish.setText("Blowfish");
        PrivateKey.add(Blowfish);

        AES.setText("AES");
        PrivateKey.add(AES);

        jMenuBar1.add(PrivateKey);

        Help.setText("Help");

        Dev.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        Dev.setText("Developers");
        Help.add(Dev);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   String sha256_return(String message) throws NoSuchAlgorithmException {
    
    MessageDigest digest = MessageDigest.getInstance("SHA-256");
    byte[] hash = digest.digest(message.getBytes(StandardCharsets.UTF_8));
       
    StringBuilder hexString = new StringBuilder();
    for (int i = 0; i < hash.length; i++) {
    String hex = Integer.toHexString(0xff & hash[i]);
    if(hex.length() == 1) hexString.append('0');
        hexString.append(hex);
    }
       
    return hexString.toString();
    
   }
   
    private void AtbashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtbashActionPerformed
    MainPanel.removeAll();
    MainPanel.repaint();
    MainPanel.revalidate();

    MainPanel.add(AtbashPanel);
    MainPanel.repaint();
    MainPanel.revalidate();
    }//GEN-LAST:event_AtbashActionPerformed

    private void CaesarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_CaesarComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CaesarComponentAdded

    private void CaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaesarActionPerformed
        
    MainPanel.removeAll();
    MainPanel.repaint();
    MainPanel.revalidate();

    MainPanel.add(CaesarPanel);
    MainPanel.repaint();
    MainPanel.revalidate();
    
    }//GEN-LAST:event_CaesarActionPerformed

    private void VigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VigenereActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(VigenerePanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_VigenereActionPerformed

    private void ECBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECBActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(ECBPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_ECBActionPerformed

    private void Answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1ActionPerformed

    private void ECB_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECB_ButtonActionPerformed
        String val1 = Answer1.getText();
        String val2 = "NEVER USE ECB";
        
        if(Objects.equals(val1, val2))
        {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();

            MainPanel.add(Correct_ECB);
            MainPanel.repaint();
            MainPanel.revalidate();
        }
        else
            System.out.println("FALSE");
        
        System.out.println(val1);
    }//GEN-LAST:event_ECB_ButtonActionPerformed

    private void FeistelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeistelActionPerformed
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();

            MainPanel.add(FeistelPanel);
            MainPanel.repaint();
            MainPanel.revalidate();
    }//GEN-LAST:event_FeistelActionPerformed

    private void Feistel_EntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feistel_EntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Feistel_EntryActionPerformed

    private void Feistel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feistel_ButtonActionPerformed
        String val1 = Feistel_Entry.getText();
        String val2 = "01010100";
        
        if(Objects.equals(val1, val2))
            JOptionPane.showMessageDialog(null, "You are correct!!", "CORRECT", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "This is not correct. Try again.", "INCORRECT", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Feistel_ButtonActionPerformed
/*-----------------------------------------------*/
/*THESE ARE BUILT IN PRIMITIVES FOR THE TEXTFIELDS*/
/*-----------------------------------------------*/
    private void SubmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmissionActionPerformed

    private void Submission1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submission1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Submission1ActionPerformed

    private void Submission2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submission2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Submission2ActionPerformed
/*-----------------------------------------------*/
/*------END OF PRIMITIVES------------------------*/
/*-----------------------------------------------*/
    
    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(WelcomePanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_HomeActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String val1 = Submission.getText();
        String val2 = "experience is the teacher of all things";
        
        if(Objects.equals(val1, val2))
            JOptionPane.showMessageDialog(null, "You are correct!!", "CORRECT", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "This is not correct. Try again.", "INCORRECT", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_SubmitActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
        String val1 = Submission1.getText();
        String val2 = "nothing about this is secure";
        
        if(Objects.equals(val1, val2))
            JOptionPane.showMessageDialog(null, "You are correct!!", "CORRECT", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "This is not correct. Try again.", "INCORRECT", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Submit1ActionPerformed

    private void Submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2ActionPerformed
        String val1 = Submission2.getText();
        String val2 = "this isnt a caesar cipher";
        
        if(Objects.equals(val1, val2))
            JOptionPane.showMessageDialog(null, "You are correct!!", "CORRECT", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "This is not correct. Try again.", "INCORRECT", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Submit2ActionPerformed

    private void RSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSAActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(RSAPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_RSAActionPerformed

    private void RSAA1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSAA1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSAA1_1ActionPerformed

    private void ELGamalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELGamalActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(ElGamalPanel);
        MainPanel.repaint();
        MainPanel.revalidate();       
    }//GEN-LAST:event_ELGamalActionPerformed

    private void EGB1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EGB1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EGB1_1ActionPerformed

    private void EGA1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EGA1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EGA1_1ActionPerformed

    private void EGA1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EGA1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EGA1_2ActionPerformed

    private void SHA_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHA_ButtonActionPerformed
        try {  
            FormerSHA.setText(SHA_Output.getText());
            String sha_output = sha256_return(SHA_Text.getText());
            SHA_Output.setText(sha_output);
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SHA_ButtonActionPerformed

    private void SHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHAActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(SHAPanel);
        MainPanel.repaint();
        MainPanel.revalidate();      
    }//GEN-LAST:event_SHAActionPerformed

    private void DiffieHellmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiffieHellmanActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DHPanel);
        MainPanel.repaint();
        MainPanel.revalidate();  
    }//GEN-LAST:event_DiffieHellmanActionPerformed

    private void DHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DHButtonActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DHPanel1);
        MainPanel.repaint();
        MainPanel.revalidate();  
    }//GEN-LAST:event_DHButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DHPanel2);
        MainPanel.repaint();
        MainPanel.revalidate();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DHPanel3);
        MainPanel.repaint();
        MainPanel.revalidate();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DHPanel4);
        MainPanel.repaint();
        MainPanel.revalidate();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DHPanel5);
        MainPanel.repaint();
        MainPanel.revalidate();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TripDESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripDESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TripDESActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F1ActionPerformed

    private void CBC_MACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBC_MACActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(CBCMAC);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_CBC_MACActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(F1.isSelected() && T2.isSelected() && T3.isSelected() && F4.isSelected() && F5.isSelected()) 
           JOptionPane.showMessageDialog(null, "You are correct!!", "CORRECT", JOptionPane.INFORMATION_MESSAGE);
       else
           JOptionPane.showMessageDialog(null, "Try again", "INCORRECT", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AES;
    private javax.swing.JTextField Answer1;
    private javax.swing.JMenuItem Atbash;
    private javax.swing.JPanel AtbashPanel;
    private javax.swing.JLabel AtbashTitle;
    private javax.swing.JMenu Authentication;
    private javax.swing.JMenu BlockCiphers;
    private javax.swing.JMenuItem Blowfish;
    private javax.swing.JMenuItem CBC;
    private javax.swing.JPanel CBCMAC;
    private javax.swing.JLabel CBCMACTitle;
    private javax.swing.JMenuItem CBC_MAC;
    private javax.swing.JMenuItem CHAP;
    private javax.swing.JMenuItem CTR;
    private javax.swing.JMenuItem Caesar;
    private javax.swing.JPanel CaesarPanel;
    private javax.swing.JLabel CaesarTitle;
    private javax.swing.JMenu Ciphers;
    private javax.swing.JLabel Ciphertext_Atbash;
    private javax.swing.JLabel Ciphertext_Caesar;
    private javax.swing.JLabel Ciphertext_Vigenere;
    private javax.swing.JLabel Correct1;
    private javax.swing.JPanel Correct_ECB;
    private javax.swing.JLabel Correct_Pic;
    private javax.swing.JLabel Current;
    private javax.swing.JButton DHButton;
    private javax.swing.JLabel DHDiagram;
    private javax.swing.JPanel DHPanel;
    private javax.swing.JPanel DHPanel1;
    private javax.swing.JPanel DHPanel2;
    private javax.swing.JPanel DHPanel3;
    private javax.swing.JPanel DHPanel4;
    private javax.swing.JPanel DHPanel5;
    private javax.swing.JMenuItem Dev;
    private javax.swing.JMenuItem DiffieHellman;
    private javax.swing.JMenu DigitalSignatures;
    private javax.swing.JMenuItem ECB;
    private javax.swing.JPanel ECBPanel;
    private javax.swing.JButton ECB_Button;
    private javax.swing.JLabel ECB_Picture;
    private javax.swing.JTextField EGA1_1;
    private javax.swing.JTextField EGA1_2;
    private javax.swing.JButton EGB1_1;
    private javax.swing.JButton EGB1_2;
    private javax.swing.JLabel EGQ1;
    private javax.swing.JLabel EGQ1_1;
    private javax.swing.JLabel EGQ1_2;
    private javax.swing.JMenuItem ELGamal;
    private javax.swing.JLabel ElGamalHeader;
    private javax.swing.JPanel ElGamalPanel;
    private javax.swing.JMenu EncryptionModes;
    private javax.swing.JMenuItem Entropy;
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton F5;
    private javax.swing.JLabel FSULOGO;
    private javax.swing.JLabel False;
    private javax.swing.JMenuItem Feistel;
    private javax.swing.JPanel FeistelPanel;
    private javax.swing.JButton Feistel_Button;
    private javax.swing.JTextField Feistel_Entry;
    private javax.swing.JLabel Feistel_Intro;
    private javax.swing.JLabel Feistel_Pic;
    private javax.swing.JLabel Former;
    private javax.swing.JLabel FormerSHA;
    private javax.swing.JMenu Hashing;
    private javax.swing.JMenu Help;
    private javax.swing.JMenu Home;
    private javax.swing.JMenuItem Kerberos;
    private javax.swing.JMenuItem LinearFeedback;
    private javax.swing.JMenuItem MD5;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem OneTimePad;
    private javax.swing.JMenuItem PAP;
    private javax.swing.JMenu PrivateKey;
    private javax.swing.JMenu PublicKey;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question3_1;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JLabel Question5_1;
    private javax.swing.JLabel Question5_2;
    private javax.swing.JMenuItem RC5;
    private javax.swing.JMenuItem RSA;
    private javax.swing.JTextField RSAA1_1;
    private javax.swing.JTextField RSAA1_2;
    private javax.swing.JTextField RSAA1_3;
    private javax.swing.JButton RSAB1_1;
    private javax.swing.JButton RSAB1_2;
    private javax.swing.JButton RSAB1_3;
    private javax.swing.JLabel RSAHeader;
    private javax.swing.JPanel RSAPanel;
    private javax.swing.JLabel RSAQ1;
    private javax.swing.JLabel RSAQ1_1;
    private javax.swing.JLabel RSAQ1_2;
    private javax.swing.JLabel RSAQ1_3;
    private javax.swing.JMenuItem RSASignature;
    private javax.swing.JMenuItem SHA;
    private javax.swing.JTextField SHAA1;
    private javax.swing.JTextField SHAA2;
    private javax.swing.JTextField SHAA3;
    private javax.swing.JButton SHAB1;
    private javax.swing.JButton SHAB2;
    private javax.swing.JButton SHAB3;
    private javax.swing.JPanel SHAPanel;
    private javax.swing.JLabel SHAQ1;
    private javax.swing.JLabel SHAQ2;
    private javax.swing.JLabel SHAQ3;
    private javax.swing.JButton SHA_Button;
    private javax.swing.JLabel SHA_Header1;
    private javax.swing.JLabel SHA_Output;
    private javax.swing.JLabel SHA_Questions;
    private javax.swing.JTextField SHA_Text;
    private javax.swing.JMenuItem SSynchronizing;
    private javax.swing.JMenu StreamCiphers;
    private javax.swing.JTextField Submission;
    private javax.swing.JTextField Submission1;
    private javax.swing.JTextField Submission2;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Submit1;
    private javax.swing.JButton Submit2;
    private javax.swing.JMenu SubstitutionCiphers;
    private javax.swing.JMenuItem Synchronous;
    private javax.swing.JRadioButton T1;
    private javax.swing.JRadioButton T2;
    private javax.swing.JRadioButton T3;
    private javax.swing.JRadioButton T4;
    private javax.swing.JRadioButton T5;
    private javax.swing.JMenuItem TripDES;
    private javax.swing.JLabel True;
    private javax.swing.JMenuItem Vigenere;
    private javax.swing.JPanel VigenerePanel;
    private javax.swing.JLabel VigenereTitle;
    private javax.swing.JLabel Warning;
    private javax.swing.JLabel Warning1;
    private javax.swing.JLabel Warning2;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
